version: '3.3'


services:
    mtproto:
        image: cosmickitten/tgproxyservice
        restart: always
        container_name: mtproto
        volumes:
            - ./proxy-config:/data
        environment: 
            SECRET: '1417f335768d5092833eb831012ad1a1'
        ports:
             - 4433:443
             - 80:80 
     


